### ISSUE TITLE
missing git tag / github release

### ISSUE THREAD

**Issue by anthraxx** [FelipeEcker/nsoq#1]
Hey,
on your homepage you are offering a tarball with version 1.9.5 which is newer then the current git version here on github.
I would highly appreciate it to sync this git repository and also push a 1.9.5 tag on github (so there is a corresponding tarball for the 1.9.5 source release also on github).
I'm using the git tags as upstream watch to get a notification if new versions are released and create a new package accordingly from within the github tarball of that tag.
thanks in advise,
anthraxx

**Comment by anthraxx** [comment]
seriously no response until now? come on.... its just issuing 'git tag' once

**Comment by FelipeEcker** [comment]
Done.
My apologies for the inconvenience.

[ ]'s

**Comment by anthraxx** [comment]
thank you very much :+1:
